# This is a basic workflow to help you get started with Actions

name: Build seed.iso files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "draft" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: install-build-dependencies
        shell: bash
        run: sudo apt install -y cloud-image-utils

      # Runs a single command using the runners shell
      - name: build ISO files
        run: for server in *; do echo $server && cloud-localds $server-seed.iso $server/user-data $server/meta-data; done

      # Runs a set of commands using the runners shell
      - name: upload ISO files
        uses: actions/upload-artifact@v3
        with:
          name: ISO-Artifacts
          path: ./*.iso
